# Generated by Django 6.0.6 on 2026-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo_alerta', models.IntegerField(default=5)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
